---
# The sensor integrationThey monitor the states and conditions of a variety of entities
#
# This loads up my sensors
#
# https://www.home-assistant.io/integrations/sensor
#
binary_sensor: !include_dir_list ../binary_sensors
