---
# The default configuration integration.
#
# https://www.home-assistant.io/integrations/default_config
#
# This integration is merely a meta-integration. By itself, it does nothing,
# however, it dependent on a lot of integrations that should be loaded by
# default.
#
# For example: history, frontend, cloud, logbook, map, my, script, sun,
# zeroconf, person, scene, system_healt, and a lot more.
#
default_config: ~

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named ../themes

automation: !include ../automations.yaml
script: !include ../scripts.yaml
scene: !include ../scenes.yaml

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 365
