---
#
sensor:
  - name: "average_salon_temperature"
    unique_id: "2e8f9c46-0433-463b-815a-a7cbea0c24f1"
    unit_of_measurement: "°C"
    state: >
      {% set netatmo = states('sensor.netatmo_master_temperature') | float %}
      {% set tado = states('sensor.tado_salon_temperature') | float %}

      {{ ((netatmo + tado) / 2) | round(1, default=0) }}
