---
#
sensor:
  - name: "omie_tolls_loss_price"
    unique_id: "6cfd53de-0029-4cd3-9ecb-69665f3d9c5c"
    unit_of_measurement: "€/kWh"
    icon: "mdi:currency-eur"
    state: >
      {% set omie = states('sensor.omie_spot_price_es') | float / 1000 %}
      {% set gas = states('sensor.omie_adjustment_price_es') | float / 1000 %}
      {% set tolls = float(states('sensor.esios_tolls_cost'),0) %}

      {{ ((omie * 1.18) + gas + tolls) }}
