---
#
sensor:
  - name: "pvpc_energy_cost"
    unique_id: "83969946-8768-4227-a5d6-90227dafb903"
    unit_of_measurement: "€/kWh"
    icon: "mdi:currency-eur"
    state: >
      {% set pvpc = states('sensor.esios_pvpc') | float %}
      {% set toll = float(states('sensor.esios_tolls_cost',0)) %}

      {{ pvpc-toll  }}
    attributes:
      pvpc: {{ states('sensor.esios_pvpc') }}
      toll: {{ float(states('sensor.esios_tolls_cost',0)) }}
      price_00h: {{ state_attr('sensor.esios_pvpc','price_00h') - state_attr('sensor.esios_tolls_cost','price_00h')}}
      price_01h: {{ state_attr('sensor.esios_pvpc','price_01h') - state_attr('sensor.esios_tolls_cost','price_01h')}}
      price_02h: {{ state_attr('sensor.esios_pvpc','price_02h') - state_attr('sensor.esios_tolls_cost','price_02h')}}
      price_03h: {{ state_attr('sensor.esios_pvpc','price_03h') - state_attr('sensor.esios_tolls_cost','price_03h')}}
      price_04h: {{ state_attr('sensor.esios_pvpc','price_04h') - state_attr('sensor.esios_tolls_cost','price_04h')}}
      price_05h: {{ state_attr('sensor.esios_pvpc','price_05h') - state_attr('sensor.esios_tolls_cost','price_05h')}}
      price_06h: {{ state_attr('sensor.esios_pvpc','price_06h') - state_attr('sensor.esios_tolls_cost','price_06h')}}
      price_07h: {{ state_attr('sensor.esios_pvpc','price_07h') - state_attr('sensor.esios_tolls_cost','price_07h')}}
      price_08h: {{ state_attr('sensor.esios_pvpc','price_08h') - state_attr('sensor.esios_tolls_cost','price_08h')}}
      price_09h: {{ state_attr('sensor.esios_pvpc','price_09h') - state_attr('sensor.esios_tolls_cost','price_09h')}}
      price_10h: {{ state_attr('sensor.esios_pvpc','price_10h') - state_attr('sensor.esios_tolls_cost','price_10h')}}
      price_11h: {{ state_attr('sensor.esios_pvpc','price_11h') - state_attr('sensor.esios_tolls_cost','price_11h')}}
      price_12h: {{ state_attr('sensor.esios_pvpc','price_12h') - state_attr('sensor.esios_tolls_cost','price_12h')}}
      price_13h: {{ state_attr('sensor.esios_pvpc','price_13h') - state_attr('sensor.esios_tolls_cost','price_13h')}}
      price_14h: {{ state_attr('sensor.esios_pvpc','price_14h') - state_attr('sensor.esios_tolls_cost','price_14h')}}
      price_15h: {{ state_attr('sensor.esios_pvpc','price_15h') - state_attr('sensor.esios_tolls_cost','price_15h')}}
      price_16h: {{ state_attr('sensor.esios_pvpc','price_16h') - state_attr('sensor.esios_tolls_cost','price_16h')}}
      price_17h: {{ state_attr('sensor.esios_pvpc','price_17h') - state_attr('sensor.esios_tolls_cost','price_17h')}}
      price_18h: {{ state_attr('sensor.esios_pvpc','price_18h') - state_attr('sensor.esios_tolls_cost','price_18h')}}
      price_19h: {{ state_attr('sensor.esios_pvpc','price_19h') - state_attr('sensor.esios_tolls_cost','price_19h')}}
      price_20h: {{ state_attr('sensor.esios_pvpc','price_20h') - state_attr('sensor.esios_tolls_cost','price_20h')}}
      price_21h: {{ state_attr('sensor.esios_pvpc','price_21h') - state_attr('sensor.esios_tolls_cost','price_21h')}}
      price_22h: {{ state_attr('sensor.esios_pvpc','price_22h') - state_attr('sensor.esios_tolls_cost','price_22h')}}
      price_23h: {{ state_attr('sensor.esios_pvpc','price_23h') - state_attr('sensor.esios_tolls_cost','price_23h')}}
