---
#
sensor:
  - name: "average_nora_temperature"
    unique_id: "c3c63ba0d-7a78-4587-aecc-6d29be9e0456"
    unit_of_measurement: "°C"
    state: >
      {% set netatmo = states('sensor.netatmo_2_temperature') | float %}
      {% set tado = states('sensor.tado_nora_temperature') | float %}

      {{ ((netatmo + tado) / 2) | round(1, default=0) }}
