---
#
#   sensor.esios_pvpc = €/kWh
#   sensor.omie_adjustment_price_es = today_hours:'2023-11-11T00:00:00+01:00': 0
#   sensor.omie_spot_price_es = today_hours.'2023-11-11T00:00:00+01:00': 19.08
#

sensor:
  - name: "pvpc_energy_cost"
    unique_id: "83969946-8768-4227-a5d6-90227dafb903"
    unit_of_measurement: "€/kWh"
    icon: "mdi:currency-eur"
    state: >
      {% set pvpc = states('sensor.esios_pvpc') | float %}
      {% set toll = float(states('sensor.esios_tolls_cost',0)) %}

      {{ pvpc - toll }}
    attributes:
      price_00h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_00h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_00h'],0) %}
        {{ pvpc - toll }}
      price_01h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_01h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_01h'],0) %}
        {{ pvpc - toll }}
      price_02h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_02h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_02h'],0) %}
        {{ pvpc - toll }}
      price_03h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_03h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_03h'],0) %}
        {{ pvpc - toll }}
      price_04h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_04h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_04h'],0) %}
        {{ pvpc - toll }}
      price_05h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_05h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_05h'],0) %}
        {{ pvpc - toll }}
      price_06h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_06h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_06h'],0) %}
        {{ pvpc - toll }}
      price_07h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_07h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_07h'],0) %}
        {{ pvpc - toll }}
      price_08h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_08h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_08h'],0) %}
        {{ pvpc - toll }}
      price_09h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_09h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_09h'],0) %}
        {{ pvpc - toll }}
      price_10h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_10h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_10h'],0) %}
        {{ pvpc - toll }}
      price_11h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_11h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_11h'],1) %}
        {{ pvpc - toll }}
      price_12h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_12h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_12h'],1) %}
        {{ pvpc - toll }}
      price_13h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_13h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_13h'],1) %}
        {{ pvpc - toll }}
      price_14h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_14h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_14h'],1) %}
        {{ pvpc - toll }}
      price_15h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_15h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_15h'],1) %}
        {{ pvpc - toll }}
      price_16h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_16h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_16h'],1) %}
        {{ pvpc - toll }}
      price_17h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_17h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_17h'],1) %}
        {{ pvpc - toll }}
      price_18h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_18h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_18h'],1) %}
        {{ pvpc - toll }}
      price_19h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_19h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_19h'],1) %}
        {{ pvpc - toll }}
      price_20h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_20h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_20h'],0) %}
        {{ pvpc - toll }}
      price_21h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_21h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_21h'],2) %}
        {{ pvpc - toll }}
      price_22h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_22h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_22h'],2) %}
        {{ pvpc - toll }}
      price_23h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_23h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_23h'],2) %}
        {{ pvpc - toll }}
