---
#
sensor:
  - name: "average_dormitorio_temperature"
    friendly_name: "Media temperatura dormitorio"
    unique_id: "f4a3f583-9b22-4b12-b99f-a8b95ca342ea"
    unit_of_measurement: "°C"
    state: >
      {% set netatmo = states('sensor.netatmo_1_temperature') | float %}
      {% set tado = states('sensor.tado_dormitorio_temperature') | float %}

      {{ ((netatmo + tado) / 2) | round(1, default=0) }}
