---
#
sensor:
  - name: "Precio OMIE con Peajes y Perdidas"
    unit_of_measurement: "€/kWh"
    icon: "mdi:currency-eur"
    state: >
      {% set omie = states('sensor.omie_spot_price_es') | float / 1000 %}
      {% set gas = states('sensor.omie_adjustment_price_es') | float / 1000 %}
      {% set tolls = states('sensor.esios_tolls_cost') | float %}

      {{ ((omie * 1.18) + gas + tolls) }}
