---
#
sensor:
  - name: "pvpc_energy_cost"
    unique_id: "83969946-8768-4227-a5d6-90227dafb903"
    unit_of_measurement: "€/kWh"
    icon: "mdi:currency-eur"
    state: >
      {% set pvpc = states('sensor.esios_pvpc') | float %}
      {% set toll = float(states('sensor.esios_tolls_cost',0)) %}

      {{ pvpc - toll }}
    attributes:
      price_00h: >
        {% set pvpc = states.sensor.esios_pvpc.attributes['price_00h'] | float %}
        {% set toll = float(states.sensor.esios_tolls_cost.attributes['price_00h'],0) %}
        {{ pvpc - toll }}
